<?php
    
    namespace app\Controller;

    use Alnazer\Easyapi\behaviours\Auth\MultiAuth;
    use Alnazer\Easyapi\behaviours\Auth\BasicAuth;
    use Alnazer\Easyapi\behaviours\Auth\BearerAuth;
    use Alnazer\Easyapi\helpers\Cache;
    use Alnazer\Easyapi\System\Application;
    use Alnazer\Easyapi\System\Controller;
    use app\Models\User;

    class SiteController extends Controller
    {

        public function behaviour($behaviours = [])
        {
            $behaviours["auth"] = [
                "class"=> MultiAuth::class,
                'methods' => [
                    BasicAuth::class,
                    BearerAuth::class,
                ],
                "execute" => ["index"]
            ];

            return parent::behaviour($behaviours); // TODO: Change the autogenerated stub
        }

        public function index($id = null,$name = null,$mobile = null){
            //Cache::add(range(1,20));
            Cache::get("762e8fb79cf548df22ad8071ba8ebc2b40760c6ef57c47934325218b48f4");
           return [
               'id'=> $id,
               "name" => $name,
               'mobile' => $mobile,
               'get' => Application::$app->request->get(),
               //'findBy' => User::where('username', "admin","like")->all(),
               /*"all"=>User::select(["id ","username ","id "])->all(),
               "all_selec"=>User::select("*")->whereIn("id",[1,2,3])->all(),
               "insert" => User::insert(["username"=> "admin".rand(1,20),"email"=> "hassan".rand(1,20)."@gmail.com","password"=> sha1(time()),"access_token"=>sha1(time()*time())]),
               "query"=>User::select("*")->where(["username"=> "admin","email"=> "hassan@gmail.com"])->all(),
               "queryCount"=>User::select("*")->where(["username"=> "admin","email"=> "hassan@gmail.com"])->count(),
               "one"=>User::one(),
               "last"=>User::last(),
               "count"=>User::count(),
               "first"=>User::first(),
               "inputs" => $this->request->get(),
               "name" => ["first"=> "hassan", "last" => "Attia"],
               "email" => "hassan@gmail.com",
               "mobile" => "90033807",
               "nation" => [
                   "country" => [
                       "name" => "egypt",
                       "code" => "EG",
                       "curancy" => [
                           "title" => "Egypt bound",
                           "ex" => 3.0,
                       ]
                   ]
               ],*/
           ];
        }

        public function beforeCall($action = [])
        {
            return parent::beforeCall($action); // TODO: Change the autogenerated stub
        }
    }