<?php
    
    namespace app\Controller;
    
    use Alnazer\Easyapi\System\Controller;
    use app\Models\User;

    class SiteController extends Controller
    {

        public function index(){
    
           return [
               "query"=>User::select("*")->where(["username"=> "admin","email"=> "hassanaliksa@gmail.com"])->all(),
               "queryCount"=>User::select("*")->where(["username"=> "admin","email"=> "hassanaliksa@gmail.com"])->count(),
               "all"=>User::all(),
               "one"=>User::one(),
               "last"=>User::last(),
               "count"=>User::count(),
               "first"=>User::first(),
               "inputs" => $this->request->get(),
               "name" => ["first"=> "hassan", "last" => "Attia"],
               "email" => "hassan@gmail.com",
               "mobile" => "90033807",
               "nation" => [
                   "country" => [
                       "name" => "egypt",
                       "code" => "EG",
                       "curancy" => [
                           "title" => "Egypt bound",
                           "ex" => 3.0,
                       ]
                   ]
               ],
           ];
        }
        
        public function beforeCall($action = [])
        {
            return parent::beforeCall($action); // TODO: Change the autogenerated stub
        }
    }