<?php
    namespace app\Controller;
    use Alnazer\Easyapi\System\Controller;

    class UserController extends Controller
    {
        
    
        public function login()
        {
            return 1;
        }
        public function update()
        {
            return 1;
        }
        public function beforeCall($action = [])
        {
            return parent::beforeCall($action); // TODO: Change the autogenerated stub
        }
    }